# variables are defined in .env file
projects:
  campfire-export:
    schema:
      - "https://niantic-social-api.nianticlabs.com/graphql":
          headers:
            Authorization: Bearer ${TOKEN}
    documents: "server/campfire/queries/**/*.graphql"
